moji/account/urls.py
from django.conf.urls import url
#from django.contrib.auth.views import login, logout, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from . import views
from django.contrib.auth import views as auth_views

app_name = 'account'
urlpatterns = [
    url(r'^post/file/$',views.postFile,name='filepost'),
    url(r'^unauth/$',views.unauthed,name='unauthed'),
    url(r'^auth/$',views.authUser),
    url(r'^lastseen/$',views.send_lastSeen),
    url(r'^update/profile/$',views.update_user_or_profile),
    url(r'^create/user/$',views.create_user_and_profile),
    url(r'^manage/block_unblock/$',views.block_or_unblock_user),
    url(r'^delete/user/$', views.delete_user_and_profile),
    url(r'^get/user/(?P<username>\w+)/$',views.get_user_and_profile_with_content),
    url(r'^update/authed_password/$',views.change_user_password),
    #url(r'^get/follow_request/$', views.get_all_follow_requests),
    #url(r'^post/follow_request/$',views.send_follow_request),
    #url(r'^get/requests/$', views.manage_follow_request),
    #url(r'^delete/follow_request/$',views.unsend_follow_request),
    url(r'^get/following/$',views.get_following),
    url(r'^get/followers/$',views.get_followers),
    url(r'^post/remove_follower/$', views.remove_follower)
]
"""
urlpatterns = [
    url(r'^profile/(?P<name>\w+)/$', views.ViewProfile, name='ProfileView'),
    url(r'^login/$', login, {'template_name': 'pages/2/login.html'}, name='login'),
    url(r'^logout/$', logout, {'template_name': 'pages/2/loggedout.html'}, name='logout'),
    url(r'^following/(?P<name>\w+)/unfollowed/$', views.unfollowUser, name='Unfollow'),
    url(r'^following/requests/(?P<name>\w+)/$', views.detailRequests, name='detailAcceptance'),
    url(r'^following/requests/(?P<name>\w+)/accept/$', views.editRequests, name='editAcceptance'),
    url(r'^following/requests/(?P<name>\w+)/decline/$', views.deleteRequests, name='deleteAcceptance'),
    url(r'^following/requests/(?P<name>\w+)/sent/$', views.makeRequests, name='makeAcceptance'),
    url(r'^following/requests/$', views.listRequests, name='listAcceptance'),
    url(r'^register/$', views.register, name='Register'),
    url(r'^delete/$', views.deleteProfile, name='DeleteProfile'),
    url(r'^profile-edit/$', views.updateProfile, name='update'),
    url(r'^change-password/$', views.change_password, name='change_password'),
    url(r'^reset-password/$', PasswordResetView.as_view(), name='password_reset'),
    url(r'^reset-password/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    url(r'^blocked/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.blockUser, name='blockUser'),
    url(r'unblocked/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.unblockUser, name='unblockUser'),
    url(r'preview/process/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.previewRemoveAdd, name='PreviewProcess'),
    #url(r'preview/remove/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.PreviewRemove, name='removePreview'),


#password reset  {'post_reset_redirect': 'account:password_reset_complete'}  {'post_reset_redirect': 'account:password_reset_done'},
]
"""

moji/banking/urls.py
from django.conf.urls import url
from . import views

app_name = 'banking'

urlpatterns = [
    url(r'^connect/$', views.connectCreation, name='preConnect'),
    url(r'^conf/$', views.confConnect, name='confConnect'),
    url(r'^precard/$', views.precard, name='precard'),
    url(r'^card-modify/$', views.modifyCard, name='modifyCard'),
    #url(r'^card-motify/$', views.motifyCard, name='motifyCard')
]

moji/content/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views
"""
app_name = 'content'

urlpatterns = [
    url(r'^detail/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailContent, name='detail'),
#post create
    url(r'^create/post/$', views.postCreate.as_view(), name='CreatePost'),
#video create
    url(r'^create/video/$', views.videoCreate.as_view(), name='CreateVideo'),
#tweet create
    url(r'^create/tweet/$', views.tweetCreate.as_view(), name='CreateTweet'),
#delete content
    url(r'^delete/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteContent, name='DeleteContent'),
#delete comment
    url(r'^delete/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteComment, name='DeleteComment'),
#delete like
    url(r'^delete/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteLike, name='DeleteLike'),
#comment create
    url(r'^create/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.commentCreate, name='CreateComment'),
#comment create
    url(r'^create/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.likeCreate, name='CreateLike'),

    url(r'^unlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeLike, name='unLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createLike, name='createLike'),

    url(r'^CMunlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeCommentLike, name='Comment_unLike'),

    url(r'^CMlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createCommentLike, name='Comment_createLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailPlaylist, name='detailPlaylist'),

    url(r'^addPlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.addContentToPlaylist, name='addContentPlaylist'),

    url(r'^removePlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeContentFromPlaylist, name='removeContentPlaylist'),

    url(r'^delete_playlist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deletePlaylist, name='deletePlaylist'),

    url(r'^creating_playlist/$', views.createPlaylist, name='createPlaylist'),

]
"""

moji/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index ,name='home'),
    url(r'^bug/$', views.emailReport.as_view(), name='bug'),
    url(r'^search/$', views.SearchUser, name='search'),
    url(r'^discover/$', views.discoverView, name='discovered'),
    url(r'^discover/(?P<genre>\w+)/$', views.discoverGenre, name='genre'),
    url(r'^about/$', views.aboutUs, name='about'),
    url(r'^how-we-work/$', views.Hww, name='hww'),
    url(r'^join/$', views.Join, name='join'),

]

moji/moji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    #url(r'^content/', include('content.urls')),
    #url(r'^home/', include('home.urls')),
    #url(r'^product/', include('product.urls')),
    #url(r'^banking/', include('banking.urls')),
    #url(r'^notification/', include('notif.urls')),
    url(r'', include('django.contrib.auth.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moji/notif/urls.py
from django.conf.urls import url
from . import views

app_name='notif'

urlpatterns = [
    url(r'^edit/notification/$', views.editNotif, name='editNotif'),
]

moji/pages/templates/pages/1/homeAuth.html
<h1>FANMOJI</h1><p>patched .03</p>
<a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'account:logout' %}">Logout</a>
<a href="{{user.profile.get_absolute_url}}">{{user.username}}</a>
<a href="{% url 'content:CreateTweet' %}">Tweet</a>
<a href="{% url 'content:CreatePost' %}">Post</a>
<a href="{% url 'content:CreateVideo' %}">Video</a>
<a href="{% url 'home:discovered' %}">Discover</a>

<br>
<form method='GET' action="{% url 'home:search' %}"  role="search" >
    <input type="text" value='{{request.GET.q}}' class="form-control" name='q' placeholder="Search.."/>
      <button type="submit" value='Search'>Search</button>
</form>

{% for i in following_query %}
<p>------------</p>
{{i.user.username}}
{{i.date}}
{{i.typeContent}}
<p>------------</p>
{% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if following_query.has_previous %}
            <a href="?page={{ following_query.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ following_query.number }} of {{ following_query.paginator.num_pages }}.
        </span>

        {% if following_query.has_next %}
            <a href="?page={{ following_query.next_page_number }}">more</a>
        {% endif %}
    </span>
</div>

moji/pages/templates/pages/1/homeunAuth.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'account:Register' %}">Sign Up</a>
<a href="{% url 'account:login' %}">Login</a>
<a href="{% url 'home:about' %}">About</a>
<a href="{% url 'home:hww' %}">How we work</a>

moji/pages/templates/pages/1/ownerprofile.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'account:update' %}">edit profile</a>
<a href="{% url 'notif:editNotif' %}">manage notifications</a>
<h1>Profile</h1>
<p>Full name: {{ user.first_name }}  {{ user.last_name }}</p>

{% if user.stripecustomer %}
<a href="{% url 'banking:precard' %}">replace billing info</a>
{% else %}
<a href="{% url 'banking:precard' %}">add billing info</a>
{% endif %}

{% if user.celeb == True %}
<b>user is a influencer</b>
<a href="{% url 'product:stripeview' %}"></a>
{% else %}
<a href="">become a celeb</a>
{% endif %}

{% if user.profile.bio != None %}
<p>Bio: {{ user.profile.bio }}</p>
{% else %}
<p>No bio</p>
{% endif %}

<p><a href="{{ user.link1 }}">{{ user.link1 }}</a></p>
<p><a href="{{ user.link2 }}">{{ user.link2 }}</a></p>

{% if user.location != None %}
<p>Location: {{ user.location }}</p>
{% else %}
{% endif %}

{% if user.profile.pic %}
<img src="{{ user.profile.pic.url }}" width="240">
{% endif %}


<br>
<p>{{user.username}}'s content</p>
  <ul>
      {% for iii in user.content_set.all %}
        <li><a href="{{ iii.get_absolute_url }}">{{ iii.typeContent }}</a></li>
      {% if iii.preview == False %}
        <li><a href="{% url 'account:PreviewProcess' uuid=iii.uuid %}">add to previews</a></li>
      {% else %}
        <li><a href="{% url 'account:PreviewProcess' uuid=iii.uuid %}">remove to previews</a></li>
      {% endif %}
      {% empty %}
        <li>No Contents</li>
      {% endfor %}
  </ul>


{% if user.requested.all %}
<a href="{% url 'account:listAcceptance' %}">view requests</a>
{% endif %}

<p>Following</p>
  <ul>
      {% for i in user.profile.following.all %}
      <li><a href="{{ i.get_absolute_url }}">{{ i.username }}</a></li>
      {% empty %}
      <li>follows no one</li>
      {% endfor %}
  </ul>
<br>

<p>Followers</p>
  <ul>
      {% for ii in user.followed_by.all %}
      <li><a href="{{ ii.get_absolute_url }}">{{ ii.user.username }}</a></li>
      {% empty %}
      <li>No one follows this person</li>
      {% endfor %}
  </ul>

moji/pages/templates/pages/1/paytofollow.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<h3>{{celeb.user.username}}</h3>
<h3>{{celeb.user.plan.description}}</h3>
<h3>{{celeb.user.plan.price}}</h3>

pay button
return button
if user does not have a card on file dont show them pay button, but a link to add card

moji/pages/templates/pages/1/privateprofile.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h1>Profile</h1>
<p>Full name: {{ user.first_name }}  {{ user.last_name }}</p>
<p> Private </p>
{% if user.celeb == True %}
<b>user is a influencer</b>
{% endif %}

{% if user.profile.bio != None %}
<p>Bio: {{ user.profile.bio }}</p>
{% else %}
<p>No bio</p>
{% endif %}

{% if user.celeb == True %}
<a href="{% url 'product:tempSub' uuid=user.profile.uuid %}">Subscribe to {{user.username}}</a>
{% else %}
{% if unauthed %}
{% else %}
<a href="{% url 'account:makeAcceptance' name=user.username %}">request to follow</a>
{% endif %}
{% endif %}


<p><a href="{{ user.link1 }}">{{ user.link1 }}</a></p>
<p><a href="{{ user.link2 }}">{{ user.link2 }}</a></p>

{% if user.location != None %}
<p>Location: {{ user.location }}</p>
{% else %}
{% endif %}

{% if user.profile.pic %}
<img src="{{ user.profile.pic.url }}" width="240">
{% endif %}

moji/pages/templates/pages/1/requestdetail.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h2>Request</h2>
<p>{{req.userFrom}} wants to follow you</p>
<a href='{% url 'account:editAcceptance' name=req.userTo.username %}'>yes</a>
<a href='{% url 'account:deleteAcceptance' name=req.userTo.username %}'>no</a>

moji/pages/templates/pages/1/unfollow.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

{% if user.celeb == true %}
<h2>are you sure you want to cancel your subscription, the remainder of your subscription will be active till the end of term</h2><a href="{% url %}">yes</a>
{% else %}
<h2>are you sure you want to Unfollow</h2><a href="{% url %}">yes</a>
{% endif %}

<a href="{% url %}">no</a>

moji/pages/templates/pages/1/viewprofile.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h1>Profile</h1>
<p>Full name: {{ user.first_name }}  {{ user.last_name }}</p>

{% if user.celeb == True %}
<b>user is a influencer</b>
<a href="{% url 'product:SendTip' %}">send a gift</a>
{% endif %}

{% if user.profile.bio != None %}
<p>Bio: {{ user.profile.bio }}</p>
{% else %}
<p>No bio</p>
{% endif %}

{% if user in request.user.following and user.celeb == False %}
<a href='{% url 'account:Unfollow' name=user.username %}'>Unfollow</a>
{% elif user in request.user.following and user.celeb == True %}
<a href='{% url 'product:cancelSub' name=user.uuid %}'>Cancel Subscription</a>
{% endif %}


<p><a href="{{ user.link1 }}">{{ user.link1 }}</a></p>
<p><a href="{{ user.link2 }}">{{ user.link2 }}</a></p>

{% if user.location != None %}
<p>Location: {{ user.location }}</p>
{% else %}
{% endif %}

{% if user.profile.pic %}
<img src="{{ user.profile.pic.url }}" width="240">
{% endif %}


<br>
<p>{{user.username}}'s content</p>
  <ul>
      {% for iii in user.content_set.all %}
      <li><a href="{{ iii.get_absolute_url }}">{{ iii.caption }}</a></li>
      {% empty %}
      <li>No Contents</li>
      {% endfor %}
  </ul>

<p>follow request</p>
  <ul>
      {% for iiii in user.requested.all %}
      <li><a href="{{ iiii.get_absolute_url }}">{{ iiii.userFrom.username }}</a></li>
      {% empty %}
      <li>No Contents</li>
      {% endfor %}
  </ul>

<p>Following</p>
  <ul>
      {% for i in user.profile.following.all %}
      <li><a href="{{ i.get_absolute_url }}">{{ i.username }}</a></li>
      {% empty %}
      <li>follows no one</li>
      {% endfor %}
  </ul>
<br>

<p>Followers</p>
  <ul>
      {% for ii in user.followed_by.all %}
      <li><a href="{{ ii.get_absolute_url }}">{{ ii.user.username }}</a></li>
      {% empty %}
      <li>No one follows this person</li>
      {% endfor %}
  </ul>

<a href="{% url 'account:blockUser' uuid=user.profile.uuid %}">block user</a>