moji/content/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views
"""
app_name = 'content'

urlpatterns = [
    url(r'^detail/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailContent, name='detail'),
#post create
    url(r'^create/post/$', views.postCreate.as_view(), name='CreatePost'),
#video create
    url(r'^create/video/$', views.videoCreate.as_view(), name='CreateVideo'),
#tweet create
    url(r'^create/tweet/$', views.tweetCreate.as_view(), name='CreateTweet'),
#delete content
    url(r'^delete/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteContent, name='DeleteContent'),
#delete comment
    url(r'^delete/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteComment, name='DeleteComment'),
#delete like
    url(r'^delete/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteLike, name='DeleteLike'),
#comment create
    url(r'^create/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.commentCreate, name='CreateComment'),
#comment create
    url(r'^create/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.likeCreate, name='CreateLike'),

    url(r'^unlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeLike, name='unLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createLike, name='createLike'),

    url(r'^CMunlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeCommentLike, name='Comment_unLike'),

    url(r'^CMlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createCommentLike, name='Comment_createLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailPlaylist, name='detailPlaylist'),

    url(r'^addPlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.addContentToPlaylist, name='addContentPlaylist'),

    url(r'^removePlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeContentFromPlaylist, name='removeContentPlaylist'),

    url(r'^delete_playlist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deletePlaylist, name='deletePlaylist'),

    url(r'^creating_playlist/$', views.createPlaylist, name='createPlaylist'),

]
"""

moji/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index ,name='home'),
    url(r'^bug/$', views.emailReport.as_view(), name='bug'),
    url(r'^search/$', views.SearchUser, name='search'),
    url(r'^discover/$', views.discoverView, name='discovered'),
    url(r'^discover/(?P<genre>\w+)/$', views.discoverGenre, name='genre'),
    url(r'^about/$', views.aboutUs, name='about'),
    url(r'^how-we-work/$', views.Hww, name='hww'),
    url(r'^join/$', views.Join, name='join'),

]

moji/moji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    #url(r'^content/', include('content.urls')),
    #url(r'^home/', include('home.urls')),
    #url(r'^product/', include('product.urls')),
    #url(r'^banking/', include('banking.urls')),
    #url(r'^notification/', include('notif.urls')),
    url(r'', include('django.contrib.auth.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moji/pages/templates/pages/3/contentdetail.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h2>{{content.user}}<h2>
<h2>{{content.date}}<h2>
<h2>{{content.typeContent}}<h2>
<h2>{{content.views}}<h2>

{% if content.typeContent == 'Post' %}
<img src="{{ content.file.url }}"><img>
{% if content.file %}
<img src="{{ content.file.url }}"><img>
{% endif %}
{% elif content.typeContent == 'Video' %}
<video width="480" height="360" controls poster='{{content.thumbnail.url}}'>
<source src='{{ content.file.url }}' type='video/mp4'>
</video>
{% endif %}


<br>
<a href='{% url 'content:CreateComment' uuid=content.uuid %}'>create comment</a>

{% for i in content.comment_set.all %}
  {% if i.user == user %}
    <a href="{% url 'content:DeleteComment' uuid=i.uuid %}">delete comment</a>
    {% else %}
    <p>{{i.user}}</p>
    <p>{{i.comment}}</p>
      {% for x in i.commentLike_set.all %}
      {% if x.user == user %}
      <a href='{% url 'content:Comment_unLike' uuid=x.uuid %}'>unlike</a>
      {% else %}
      <a href='{% url 'content:Comment_createLike' uuid=content.uuid %}'>like</a>
      {% endif %}
      {% empty %}
      <a href='{% url 'content:Comment_createLike' uuid=content.uuid %}'>like</a>
      {% endfor %}
    <br>
    {% empty %}
  <p>no comments</p>
{% endfor %}

{% for x in content.like_set.all %}
  {% if x.user == user %}
    <a href='{% url 'content:unLike' uuid=x.uuid %}'>unlike</a>
  {% else %}
    <a href='{% url 'content:createLike' uuid=content.uuid %}'>like</a>
  {% endif %}
{% empty %}
<a href='{% url 'content:createLike' uuid=content.uuid %}'>like</a>
{% endfor %}

{% if content.user == user %}
<a href='{% url 'content:DeleteContent' uuid=content.uuid %}'>delete</a>
{%endif%}

moji/pages/templates/pages/3/createpost.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h2>content create</h2>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

moji/pages/templates/pages/3/deletecontent.html
<a href="{% url 'content:deletecontent' content_id={{}} %}">confirm</a>
<a href="{% url 'home:home' %}">cancel</a>