moji/content/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login, logout
from . import views
"""
app_name = 'content'

urlpatterns = [
    url(r'^detail/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailContent, name='detail'),
#post create
    url(r'^create/post/$', views.postCreate.as_view(), name='CreatePost'),
#video create
    url(r'^create/video/$', views.videoCreate.as_view(), name='CreateVideo'),
#tweet create
    url(r'^create/tweet/$', views.tweetCreate.as_view(), name='CreateTweet'),
#delete content
    url(r'^delete/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteContent, name='DeleteContent'),
#delete comment
    url(r'^delete/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteComment, name='DeleteComment'),
#delete like
    url(r'^delete/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deleteLike, name='DeleteLike'),
#comment create
    url(r'^create/comment/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.commentCreate, name='CreateComment'),
#comment create
    url(r'^create/like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.likeCreate, name='CreateLike'),

    url(r'^unlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeLike, name='unLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createLike, name='createLike'),

    url(r'^CMunlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeCommentLike, name='Comment_unLike'),

    url(r'^CMlike/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.createCommentLike, name='Comment_createLike'),

    url(r'^like/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.detailPlaylist, name='detailPlaylist'),

    url(r'^addPlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.addContentToPlaylist, name='addContentPlaylist'),

    url(r'^removePlaylist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/(?P<p_uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.removeContentFromPlaylist, name='removeContentPlaylist'),

    url(r'^delete_playlist/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.deletePlaylist, name='deletePlaylist'),

    url(r'^creating_playlist/$', views.createPlaylist, name='createPlaylist'),

]
"""

moji/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index ,name='home'),
    url(r'^bug/$', views.emailReport.as_view(), name='bug'),
    url(r'^search/$', views.SearchUser, name='search'),
    url(r'^discover/$', views.discoverView, name='discovered'),
    url(r'^discover/(?P<genre>\w+)/$', views.discoverGenre, name='genre'),
    url(r'^about/$', views.aboutUs, name='about'),
    url(r'^how-we-work/$', views.Hww, name='hww'),
    url(r'^join/$', views.Join, name='join'),

]

moji/moji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    #url(r'^content/', include('content.urls')),
    #url(r'^home/', include('home.urls')),
    #url(r'^product/', include('product.urls')),
    #url(r'^banking/', include('banking.urls')),
    #url(r'^notification/', include('notif.urls')),
    url(r'', include('django.contrib.auth.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moji/home/forms.py
from django import forms
from django.conf import settings
from django.core.mail import send_mail

class Reporter(forms.Form):
    Report = (('bug', 'bug'), ('violation', 'violation'), ('support', 'support'), 'advice', 'advice')

    email = forms.EmailField(required=True)
    message = forms.CharField(max_length=255, required=True)
    #add a choice to subject
    sub = ''

    #message = forms.ChoiceField(choices=Report)
    Subject = forms.CharField(max_length=55, required=True)

    def send_email(self):
        #subject = 'bug'
        subject = self.cleaned_data['Subject']
        message = self.cleaned_data['message']
        from_email = self.cleaned_data['email']
        recipient_list = [settings.EMAIL_HOST,]
        return send_mail(subject, message, from_email, recipient_list, fail_silently=False,)

moji/home/views.py
from django.shortcuts import render, redirect, Http404
from content.models import Content, Comment, Like
from account.models import Profile
from django.views.generic.edit import FormView
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.conf import settings
from .forms import Reporter
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q

def index(request):
    if request.user.is_authenticated():
        followers = request.user.profile.following.all()
        #THIS WOULD ADD THE CURRENT USERS POST TO THE HOME PAGE
        #a = []
        #for i in followers:
        #    a.append(i)
        #a.append(request.user)
        #ADD REQUEST.USER TO THEIR OWN FOLLOWING
        queryset_list = Content.objects.filter(user__in=followers).order_by('-date')
        pagenated_query = Paginator(queryset_list, 25)
        #use .object_list to access the item in paginator
        page = request.GET.get('page')
        try:
            if page != None and int(page) > pagenated_query.num_pages:
                following_query = pagenated_query.page(pagenated_query.num_pages)
            else:
                following_query = pagenated_query.page(page)
        except PageNotAnInteger:
            # If page is not an integer, deliver first page.
            following_query = pagenated_query.page(1)
        except EmptyPage:
            # If page is out of range (e.g. 9999), deliver last page of results.
            following_query = pagenated_query.page(paginator.num_pages)

            #check the django doc for use in templates
        return render(request, 'pages/1/homeAuth.html', {'following_query':following_query})
    else:
        return render(request, 'pages/1/homeunAuth.html')

def SearchUser(request):
    query = request.GET.get('q')
    if query:
        queryset_list = Profile.objects.filter(
        Q(user__username__icontains=query) |
        Q(location__icontains=query) |
        Q(user__first_name__icontains=query) |
        Q(user__last_name__icontains=query)
        ).distinct().exclude(user=request.user)[:16]
        print(queryset_list)
        return render(request, 'pages/7/searched.html', {'queryset_list':queryset_list})
    else:
        return None

def discoverView(request):
    page = 'Spotlight'
    users = User.objects.order_by('?')[:24]
    return render(request, 'pages/7/discover.html', {'users':users, 'page':page})

def discoverGenre(request, genre):
    page = genre
    try:
        users = Profile.objects.filter(genre_exact=genre).filter('?')[:24]
    except Profile.DoesNotExist:
        raise http404('cant find any users under this genre')
    return render(request, 'pages/7/discover.html', {'users':users, 'page':page})

def aboutUs(request):
    return render(request, 'pages/2/about.html')

def Hww(request):
    return render(request, 'pages/2/hww.html')

def Join(request):
    return render(request, 'pages/2/join.html')

class emailReport(FormView):
    template_name = 'home/contact.html'
    form_class = Reporter
    success_url = '/home/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super(emailReport, self).form_valid(form)


'''
class BugReport(emailReport):
    we dont need their email
    user makes the message, subject is always bug
    pass

class ViolationReport(emailReport):
    we dont need their email
    should just be choice:
    ex.
    illegal content
    slander
    bullying
    offensive
    missed advertised
    aggresive or endangering of human/animal
    copyright
    and then grabs a screenshot of the violation
    pass

class ContactReport(emailReport):
    user makes subject and message
    we need their email
    this is for potential users or celebs
    pass

class SupportReport(emailReport):
    user makes subject and message, and the users account
    we need their email
    this is for paid users, about their account or using the service
    pass
'''

moji/home/templates/home/SearchUser.html
{% extend 'account/base.html' %}

{% block body %}
<p>Discover Users</p>
<form method='GET' action="{% url 'home:search' %}" class="navbar-form navbar-right" role="search" >
  <div class="form-group input-group">
    <input type="text" value='{{request.GET.q}}' class="form-control" name='q' placeholder="Search.."/>
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit" value='Search'>
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
</form>
{% for i in users %}
<p>{{i.username}}</p>
{% endfor %}
{% endblock %}

moji/home/templates/home/contact.html
{% extends 'account:base.html' %}

{% block body %}
<div class=container>
<form action="" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send message" />
</form>
</div>
{% endblock %}

moji/home/templates/home/detail.html
{% extends 'account/base.html' %}
{% block body %}
<div class='container'>

<h2>{{content.user}}<h2>
<h2>{{content.date}}<h2>
<h2>{{content.typeContent}}<h2>
{% if content.typeContent == 'Post' %}
<img src="{{ content.file.url }}"><img>
{% if content.file %}
<img src="{{ content.file.url }}"><img>
{% endif %}
{% elif content.typeContent == 'Video' %}
<video width="480" height="360" controls poster='{{content.thumbnail.url}}'>
<source src='{{ content.file.url }}' type='video/mp4'>
</video>
{% endif %}


<br>
<a href='{% url 'content:CreateComment' pk=content.id %}'>create comment</a>

{% for i in content.comment_set.all %}
<p>{{i.user}}</p>
<p>{{i.comment}}</p>
<br>
{% empty %}
<p>no comments</p>
{% endfor %}

{% if content.user == request.user %}
<a href='{% url 'content:DeleteContent' id=content.id %}'></a>
{%else%}
{%endif%}
</div>

{% endblock %}

moji/home/templates/home/discover.html
{% extend 'account/base.html' %}

{% block body %}
<ul>
  <li><a href="{% url 'home:genre' genre='sports' %}">Logout</a></li>
  <li><a href="{% url 'home:genre' genre='finance' %}">Logout</a></li>
  <li><a href="{% url 'home:genre' genre='art' %}">Logout</a></li>
  <li><a href="{% url 'home:genre' genre='games' %}">Logout</a></li>
  <li><a href="{% url 'home:genre' genre='tech' %}">Logout</a></li>
  <li><a href="{% url 'home:genre' genre='education' %}">Logout</a></li>
</ul>
<form method='GET' action="{% url 'home:search' %}" class="navbar-form navbar-right" role="search" >
  <div class="form-group input-group">
    <input type="text" value='{{request.GET.q}}' class="form-control" name='q' placeholder="Search.."/>
    <span class="input-group-btn">
      <button class="btn btn-default" type="submit" value='Search'>
        <span class="glyphicon glyphicon-search"></span>
      </button>
    </span>
  </div>
</form>
<p>{{page}}</p>
{% for i in users %}
<p>{{i.username}}</p>
{% endfor %}
{% endblock %}

moji/home/templates/home/new.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap 4 Website Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"></script>
  <style>
  .fakeimg {
      height: 200px;
      background: #aaa;
  }
  </style>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="collapsibleNavbar">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
    </ul>
  </div>
</nav>

{% block f %}
{% endblock %}

<div class="jumbotron text-center" style="margin-bottom:0">
  <p>Footer</p>
</div>

</body>
</html>