moji/banking/urls.py
from django.conf.urls import url
from . import views

app_name = 'banking'

urlpatterns = [
    url(r'^connect/$', views.connectCreation, name='preConnect'),
    url(r'^conf/$', views.confConnect, name='confConnect'),
    url(r'^precard/$', views.precard, name='precard'),
    url(r'^card-modify/$', views.modifyCard, name='modifyCard'),
    #url(r'^card-motify/$', views.motifyCard, name='motifyCard')
]

moji/home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.index ,name='home'),
    url(r'^bug/$', views.emailReport.as_view(), name='bug'),
    url(r'^search/$', views.SearchUser, name='search'),
    url(r'^discover/$', views.discoverView, name='discovered'),
    url(r'^discover/(?P<genre>\w+)/$', views.discoverGenre, name='genre'),
    url(r'^about/$', views.aboutUs, name='about'),
    url(r'^how-we-work/$', views.Hww, name='hww'),
    url(r'^join/$', views.Join, name='join'),

]

moji/moji/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^account/', include('account.urls')),
    #url(r'^content/', include('content.urls')),
    #url(r'^home/', include('home.urls')),
    #url(r'^product/', include('product.urls')),
    #url(r'^banking/', include('banking.urls')),
    #url(r'^notification/', include('notif.urls')),
    url(r'', include('django.contrib.auth.urls'))
]

#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

moji/product/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'

urlpatterns = [
    url(r'^create/points/$', views.SetPoints, name='SetPoints'),
    url(r'^tipcreation/(?P<name>\w+)/$', views.SendTip, name='SendTip'),
    url(r'^sub/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.tempSub, name='tempSub'),
    url(r'^subscription/(?P<uuid>[\w]{8}(-[\w]{4}){3}-[\w]{12})/$', views.addSub, name='addSub'),
    url(r'^create/plan/$', views.CreatePlan.as_view(), name='CreatePlan'),
    url(r'^update/points/$', views.PointsUpdate.as_view(), name='PointsUpdate'),
    url(r'^cancellation/(?P<name>\w+)/$', views.cancelSub, name='cancelSub'),
    url(r'^removed/$', views.removeUser, name='removeUser'),
    url(r'^payout-account/$', views.viewStripe, name='stripeview'),
    #url(r'^success/$', views.success, name='success')

]
#7dfc7774-9345-4622-938f-c83a08edb4f5

moji/pages/templates/pages/5/addplan.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<h3>create a plan</h3>
<form action="" method="post">{% csrf_token %}
     {{ form.as_p }}
     <input type="submit" value="Save" />
</form>

moji/pages/templates/pages/5/addpreview.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<h2>add preview</h2>
<form action="" method="post" >{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

moji/pages/templates/pages/5/connect.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<a href="https://connect.stripe.com/express/oauth/authorize?redirect_uri='https://fans2000.herokuapp.com/banking/conf'&client_id=ca_Dl0OaOtZqQ5sT6uDiI4iKaOsAGHkHx2I"
&state=verified>connect</a>

moji/pages/templates/pages/5/createstripe.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<a href="{% url 'banking:precard' %}"></a>

moji/pages/templates/pages/5/editprofile.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<h2>account update/edit</h2>
<form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.as_p }}
    {{ form1.as_p }}
    <input type="submit" value="Save" />
</form>

moji/pages/templates/pages/5/removepreview.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

moji/pages/templates/pages/5/sendtip.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h2>account update/edit</h2>
{% if user.StripeCustomer != None %}
<form action="" method="post" >{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% else %}
<a href="{% url 'banking:addCard' %}">add card</a>
{% endif %}

moji/pages/templates/pages/5/success.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
{% if error %}
{{error}}
{% else %}
<p>payment successful</p>
{% endif %}
{% if name %}
<a href="{{name.getabsoluteurl}}">{{name.username}}</a>
{% endif %}

moji/pages/templates/pages/5/tempsub.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>

<h3>{{celeb.price}}</h3>
<h3>{{celeb.description}}</h3>


<a href="{% url 'product:addSub' uuid=user.profile.uuid %}">confirm subscription</a>

moji/pages/templates/pages/5/token.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>


<form action="{% url 'banking:addCard' %}" method="POST">{% csrf_token %}
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="pk_test_rtXYk6IQSRgZJdYQNBTTkfci"
    data-name="Stripe.com"
    data-description="Widget"
    data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
    data-locale="auto"
    data-zip-code="true"
    data-shipping-address='true'
    data-billing-address='true'>
  </script>
</form>

moji/pages/templates/pages/5/viewstripe.html
<h1>FANMOJI</h1>
<a href="{% url 'home:home' %}">Home</a>
<br>
<a href='{{stripeurl}}'>click her to be transfered to your fanmoji stripe account</a>